### ISSUE TITLE
Update niv-updater-action to v7

### ISSUE THREAD

**Issue by knl** [pbogdan/shell-cmd#19]
HI @pbogdan,

I recently [received an issue](https://github.com/knl/niv-updater-action/issues/36) for `niv-updater-action` (thanks for using it!), that nixpkgs PRs are being spammed with backreferences to update PRs coming from `niv-updater-action`. This behavior was fixed in version v6.

I noticed that you're still using v5. Could you please upgrade to v7 (or v6)?

Thanks,
Nikola

**Comment by pbogdan** [comment]
Hi @knl,

thank you for letting me know. I'll try to sort this out either this evening or tomorrow, I'm using the action on few other repos as well so I will check and update those too.

And thank you for developing and working on the action.

**Comment by pbogdan** [comment]
https://github.com/pbogdan/shell-cmd/pull/21

This should be now taken care of across all my other repos too (updated all to v7 and set up dependabot too).
Hopefully there won't be any further issues but let me know if anything does come up.

Thanks again for letting me know and sorry for the trouble.

**Comment by knl** [comment]
@pbogdan thank you for such a prompt response! No trouble on my side :)

I'll steal the approach with the dependabot, it's quite useful.
